doctrine:
    dbal:
        driver: env(DATABASE_DRIVER)
        server_version: env(DATABASE_SERVER_VERSION)
        charset: utf8mb4

        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Project:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Project/Infrastructure/Persistence/Doctrine/Mappings'
                prefix: 'App\Project\Domain\Entities'
                alias: ProjectDomainEntities



