App\Project\Domain\Entities\GithubEvent:
    type: entity
    table: github_event
    repositoryClass: App\Project\Infrastructure\Persistence\Doctrine\Repositories\GithubEventRepository
    id:
        id:
            type: bigint
            nullable: false
            id: true
            generator:
                strategy: AUTO
    indexes:
        event_type_idx:
            columns: [ type ]
        created_at_idx:
            columns: [ created_at ]
    fields:
        gitubEventId:
            type: bigint
            nullable: false
            options:
                unsigned: false
        eventType:
            type: string
            nullable: false
            length: 50
            column: type
        createdAt:
            type: date
            nullable: false
            column: created_at
        payload:
            type: json_array
            nullable: false
        comment:
            type: text
            nullable: false
